export const Strings = {
  selectWhatYouWant: 'Jelöld ki, amelyiket szeretnéd:',
  upgrades: 'Fejlesztések',
  iBuyIt: 'Megveszem',
  _1stStep: '1. lépés',
  selectWhoYouWantToAttack: 'Jelöld ki, kit szeretnél megtámadni:',
  attack: 'Támadás',
  next: 'Tovább',
  _2ndStep: '2. lépés',
  selectUnitsForFight: 'Állíts be, kiket küldesz harcba',
  iAttackIt: 'Megtámadom!',
  selectWhatYouWantToBuy: 'Jelöld ki, amelyiket szeretnéd megvenni.',
  only1BuildingCanBeBuiltAtTheSameTime: 'Egyszerre csak egy épület épülhet!',
  buildings: 'Épületek',
  fight: 'Harc',
  scoreboard: 'Ranglista',
  username: 'Felhasználónév',
  password: 'Jelszó',
  login: 'Belépés',
  haveNoAccount_: 'Nincs még fiókod?',
  register: 'Regisztráció',
  register_: 'Regisztrálj',
  profile: 'Profil',
  logout: 'Kijelentkezés',
  undersea: 'Undersea',
  confirmPassword: 'Jelszó megerősítése',
  yourCityName: 'A városod neve, amit építesz',
  alreadyHaveAccount_: 'Már van fiókod?',
  logIn: 'Lépj be',
  upgradeDescription:
    'Minden fejlesztés 15 kört vesz igénybe, egyszerre csak egy dolog fejleszthető és minden csak egyszer fejleszthető ki (nem lehet két kombájn).',
  army: 'Sereg',
  home: 'Kezdőlap',
  city: 'Városom',
  myUnits: 'Csapataim',
  passwordMustBeAtLeast4CharLong:
    'A jelszónak legalább 4 karakter hosszúnak kell lennie',
  thePasswordsShouldMatch: 'A jelszavaknak meg kell egyezniük',
  myCityName: 'Városom neve',
  youAreNotFightingAtTheMoment: 'Jelenleg egy csapatod sem harcol',
  noPlayerWithThisNameExist: 'Nincs ilyen nevű játékos',
}
